version: '3.7'

services:
  dev:
    build:
      context: .
      target: DEV
    volumes:
      - .:/app/
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh/:ro

  docs:
    build:
      context: .
      target: DOCS
    volumes:
      - .:/app/
