version: '3.7'

services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app/
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh/:ro
    environment:
      - SSH_PRIVATE_KEY_SRC

  docs:
    build:
      context: .
      target: docs
    volumes:
      - .:/app/
