name: Lint

on:
  pull_request:
  push:
  # manual trigger
  workflow_dispatch:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: markdownlint
      run: make markdownlint
    - name: prune
      run: make prune
