name: push-docker

on:
  workflow_call:
    inputs:
      tag:
        description: "The docker image tag"
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: "The dockerhub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "The dockerhub token"
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: "The docker image tag"
        required: true
        type: string

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        variant: ["actions-template-sync"]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            andyAugustin/${{ matrix.variant }}
            ghcr.io/AndreasAugustin/${{ matrix.variant }}
      - name: Build and push ${{ matrix.variant }}
        uses: docker/build-push-action@v3
        with:
          context: ./src/
          push: ${{ github.event_name != 'pull_request' }}
          tags: andreasaugustin/${{ matrix.variant }}:${{ inputs.tag }} #${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: andyAugustin/${{ matrix.variant }}
          readme-filepath: ./docs/DOCKER.md
          short-description: See https://github.com/${{ github.repository }} to have a look into the source code.
