name: test

on: [push]

jobs:

  test-implementation-job:

    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action step
        uses: ./ # Uses an action in the root directory
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          source_repo: git@github.com:AndreasAugustin/template.git
